export const GET_SUMMONER_ID = 'GET_SUMMONER_ID';
export const SET_SUMMONER_PROFILE = 'SET_SUMMONER_PROFILE';
export const GET_MASTERY_ALL_CHAMPIONS = 'GET_MASTERY_ALL_CHAMPIONS';
export const SET_MASTERY_ALL_CHAMPIONS = 'SET_MASTERY_ALL_CHAMPIONS';
export const GET_RECENT_MATCH_HISTORY = 'GET_RECENT_MATCH_HISTORY';
export const SET_RECENT_MATCH_HISTORY = 'SET_RECENT_MATCH_HISTORY';
export const SET_ERROR = 'SET_ERROR';